version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: swipto-postgres
    restart: unless-stopped
    ports:
      - "5432:5432" # host:container
    environment:
      POSTGRES_DB: swipto
      POSTGRES_USER: swipto
      POSTGRES_PASSWORD: swipto_password
      TZ: Europe/Paris
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
